# Generated by Django 6.0.6 on 2026-06-07 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('expiry_time', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='donation-images')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Completed', 'Completed')], default='Available', max_length=15)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Donation',
                'verbose_name_plural': 'Food Donations',
            },
        ),
        migrations.CreateModel(
            name='FoodClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_claimed', models.PositiveIntegerField(default=1)),
                ('amount_paid', models.FloatField(default=0)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='donations.fooddonation')),
            ],
            options={
                'verbose_name': 'Food Claim',
                'verbose_name_plural': 'Food Claims',
            },
        ),
    ]
